# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 23:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20180913_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
