# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20180913_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='first_post',
            field=models.TextField(default='test'),
        ),
    ]
