# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_topic_first_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='first_post',
            field=models.TextField(default='最初のポスト'),
        ),
    ]
