# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20180916_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='first_post',
            field=models.TextField(default='最初の投稿'),
        ),
    ]
